### ISSUE TITLE
YekApi.jar ** 这几个jar包有源码吗？

### ISSUE THREAD

**Issue by crossle** [longerian/RC4A#29]
YekApi.jar *\* 这几个jar包有源码吗？

**Comment by longerian** [comment]
有的，等一下我整理过后上传。
On May 4, 2012 1:36 AM, "Crossle" <
reply@reply.github.com>
wrote:

**Comment by crossle** [comment]
nice 。。。

https://github.com/longerian/CrowModules.git

**Comment by longerian** [comment]
后续有空我把文档再整理一下

**Comment by crossle** [comment]
en ...很不错的module
